source 'https://rubygems.org'

gem 'rake'
gem 'ruboty-alias'
gem 'ruboty-replace'
gem 'ruboty-cron'
gem 'ruboty-echo'
gem 'ruboty-slack'
gem 'ruboty-github', github: 'kokuyouwind/ruboty-github'
gem 'ruboty-redis'
