source 'https://rubygems.org'

gem 'rake'
gem 'ruboty-alias'
gem 'ruboty-replace'
gem 'ruboty-cron'
gem 'ruboty-echo'
gem 'ruboty-slack'
gem 'ruboty-github', github: 'kokuyouwind/ruboty-github'
gem 'ruboty-redis'
gem 'ruboty-bump', git: 'https://gist.github.com/52826dd3bc395e92950c60412ba2e577.git'